-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 10, 2024 at 07:09 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blog-db`
--

-- --------------------------------------------------------

--
-- Table structure for table `blog_yazi`
--

CREATE TABLE `blog_yazi` (
  `icerik_id` int(11) NOT NULL,
  `baslik` varchar(80) NOT NULL,
  `icerik` text NOT NULL,
  `aciklama` text NOT NULL,
  `dosya` varchar(355) NOT NULL,
  `kategori` int(11) NOT NULL,
  `yayinlanma_tarihi` datetime NOT NULL DEFAULT current_timestamp(),
  `yazar` varchar(50) NOT NULL,
  `yayinlayan_kullanici` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

--
-- Dumping data for table `blog_yazi`
--

INSERT INTO `blog_yazi` (`icerik_id`, `baslik`, `icerik`, `aciklama`, `dosya`, `kategori`, `yayinlanma_tarihi`, `yazar`, `yayinlayan_kullanici`) VALUES
(42, 'Kişisel Gelişim: Potansiyelimizi Keşfetme ve Dönüşüm Yolculuğu', 'Kişisel gelişim, insanların potansiyellerini keşfetme ve geliştirme sürecidir. Kendi iç dünyamızı anlamak, olumlu değişimleri gerçekleştirmek ve yaşamda daha anlamlı bir deneyim yaşamak için yapılan bir çabadır. Bu yolculuk, zihinsel, duygusal, fiziksel ve ruhsal alanlarda olumlu değişiklikler yapmayı içerir.\n\nKişisel gelişimin temelinde, kendini tanıma ve farkındalık yatmaktadır. İçsel dünyamızdaki inançlarımız, değerlerimiz, duygularımız ve düşüncelerimiz, davranışlarımızı ve hayata bakış açımızı belirler. Kendimizi tanımak, potansiyelimizi anlamak ve güçlü yanlarımızı keşfetmek için önemlidir.\n\nKişisel gelişim sürecinde, hedef belirleme ve planlama önemli adımlardan biridir. Hedefler, bizi motive eder ve bizi ileriye taşıyan bir rota çizer. Bu hedeflere ulaşmak için disiplin, azim ve sabır gereklidir.\n\nEmpati, özgüven, iletişim becerileri ve zaman yönetimi gibi sosyal ve duygusal beceriler de kişisel gelişimin önemli bir parçasıdır. Bu beceriler, başkalarıyla daha sağlıklı ilişkiler kurmamıza ve duygusal zekamızı geliştirmemize yardımcı olur.\n\nKişisel gelişim aynı zamanda öğrenme sürecidir. Kendimize ve çevremize açık olmak, yeni bilgiler ve deneyimler edinmek bizi zenginleştirir ve büyütür. Okumak, eğitim almak, seminerlere katılmak gibi faaliyetler bu süreci destekler.\n\nOlumsuz düşüncelerle baş etmek, stres yönetimi ve zorluklarla başa çıkma gibi beceriler de kişisel gelişimin önemli bir parçasıdır. Günlük hayatta karşılaştığımız zorlukları aşmak, bize içsel gücü ve esnekliği kazandırır.\n\nKişisel gelişim süreci, bir bütün olarak sağlıklı bir yaşam tarzı oluşturmaya da yönlendirir. Fiziksel sağlık, düzenli egzersiz, sağlıklı beslenme ve uyku düzeni gibi faktörler, kişisel gelişimin tamamlayıcılarıdır.\n\nKişisel gelişim, birçok alanda ilerlememizi ve başarılar elde etmemizi sağlar. Kendimize güven duymak, yaşamın zorluklarıyla daha iyi başa çıkmak, başarılarımızı kutlamak ve kendimize değer vermek, kişisel gelişimin sağladığı faydalardan sadece birkaçıdır.\n\nKişisel gelişim, yaşamın bir yolculuğudur ve her bireyin kendi hızında ve yoluyla ilerlediği bir süreçtir. İçsel dönüşümün ve büyümenin yolculuğu, insanları daha anlamlı ve tatmin edici bir hayat yaşamaya yönlendirir.', 'Kişisel gelişim, insanların potansiyellerini keşfetme ve geliştirme sürecidir. Kendi iç dünyamızı anlamak, olumlu değişimleri gerçekleştirmek ve yaşamda daha anlamlı bir deneyim yaşamak için yapılan bir çabadır.', 'kisiselgelisim.jpg', 6, '2023-07-26 22:10:45', 'ardayilmaz', 40),
(43, 'Bilim: Evrenin Sırlarını Çözen ve İnsanlığın Geleceğini Şekillendiren Yolculuk\"\n', 'Bilim, doğal dünyayı anlama ve açıklama çabasıdır. Sistemli gözlem, deneyler ve verilerin analizi yoluyla gerçekleri keşfetmeye çalışan bir disiplindir. Bilim, insan zihninin merakını tatmin eden ve insanlığın önünde sınırsız bir potansiyel sunan heyecan verici bir alanı temsil eder.\n\nBilim, doğal olayların neden ve sonuçlarını anlamak için sürekli teoriler oluşturur ve test eder. Bu süreç, insanlığın evrenin sırlarını çözme yolculuğunda büyük ilerlemelere yol açar. Astronomi, fizik, kimya, biyoloji, matematik gibi birçok bilim dalı, farklı alanlarda keşifler ve anlayışlar sağlar.\n\nBilim, insanların teknolojik ilerlemeler yapmasına ve yaşam kalitesini artırmasına yardımcı olur. İleri tıp teknolojileri, uzay keşifleri, yapay zeka, çevre koruma gibi alanlardaki bilimsel ilerlemeler, toplumun refahını ve geleceğini şekillendiren önemli faktörlerdir.\n\nBilim, gerçekliğe dayalıdır ve güvenilir verilere dayanır. Bilimsel yöntem, sistematik ve tarafsız bir yaklaşımı benimser. Bu nedenle, bilimsel bilgiler toplumun ortak mirasıdır ve sürekli olarak güncellenir ve geliştirilir.\n\nBilim, sürekli ilerleyen bir süreçtir ve teorilerin ve keşiflerin her zaman yeniden değerlendirildiği bir alanı temsil eder. Bu da bilimsel bilginin gücünü ve dinamizmini sağlar. Yanlış anlaşılmış veya hatalı bilgiler zamanla düzeltilir ve bilim dünyası daha fazla bilgiyle beslenir.\n\nBilim, etik ve güvenlik konularına da öncelik verir. Bilimsel araştırmaların yapılmasında etik kurallara uyulması, veri güvenliğinin sağlanması ve potansiyel risklerin değerlendirilmesi, bilim dünyasının temel prensiplerindendir.\n\nBilim, insanları araştırmaya ve keşfetmeye teşvik eder. Yeni nesiller, meraklarını tatmin etmek ve daha fazla bilgi edinmek için bilimsel araştırmalara ve eğitimine önem verirler.\n\nBilim, doğa olaylarını anlamanın yanı sıra insanlığın sosyal ve ekonomik sorunlarına da çözümler sunar. Sosyal bilimler, ekonomi, psikoloji gibi alanlardaki bilimsel çalışmalar, toplumun daha iyi bir gelecek inşa etmesine yardımcı olur.\n\nBilim, insanın evrene duyduğu merakın ve keşfetme arzusunun bir tezahürüdür. Bilimsel bilgi, insanın içindeki keşfetme isteğini besler ve bilinmezlikleri çözme yolculuğuna devam etmesine ilham verir. Bilim, insanlığın evrenin ve kendisinin sınırlarını genişleten büyülü bir yolculuktur.', 'Bilim, doğal dünyayı anlama ve açıklama çabasıdır. Sistemli gözlem, deneyler ve verilerin analizi yoluyla gerçekleri keşfetmeye çalışan bir disiplindir.', 'bilim.png', 1, '2023-07-26 01:20:06', 'ardayilmaz', 40),
(51, 'Teknoloji: İnsan Yaratıcılığının Sınırlarını Zorlayan Sonsuz Keşifler', 'Teknoloji, insan yaratıcılığının sınırlarını zorlayan ve sonsuz keşiflerin kapılarını açan bir güçtür. İnsanlığın tarihindeki en önemli dönüm noktalarından biri olan teknoloji, sürekli gelişerek hayatımıza büyük kolaylıklar ve yenilikler getiriyor.\n\nİlk çağlardan günümüze, insanlar hayatlarını daha iyi bir hale getirmek ve sorunları çözmek için teknolojiye başvurdular. Tekerleğin icadı, ateşin kullanımı, matbaanın keşfi gibi önemli teknolojik adımlar, insanlık tarihinde büyük devrimler yarattı.\n\nGünümüzde ise dijital devrim, teknolojinin insan yaşamına entegre olmasını sağladı. İnternetin ve bilgisayarların evrimi, dünyayı birbirine bağlayarak bilgi paylaşımını kolaylaştırdı. Mobil teknoloji, akıllı cihazlar ve yapay zeka, hayatımızı daha verimli, bağlantılı ve akıllı bir hale getirdi.\n\nTeknoloji, sağlık alanında da önemli adımlar atıyor. Medikal cihazlar, genetik araştırmalar ve dijital sağlık hizmetleri, hastalıkların erken teşhisi ve tedavisinde büyük ilerlemeler sağlıyor. Sağlık bakımı daha kişiselleştirilmiş ve etkili hale geliyor.\n\nEndüstriyel alanlarda otomasyon ve robot teknolojileri, üretim süreçlerini daha hızlı ve verimli hale getiriyor. Tarım ve tarımsal teknolojiler, gıda üretimini artırarak açlıkla mücadeleye katkı sağlıyor. Temiz enerji kaynakları ve çevre dostu teknolojiler ise çevre koruma çabalarına önemli katkılar sunuyor.\n\nTeknoloji, eğitim alanında da büyük bir değişimi beraberinde getiriyor. Uzaktan eğitim, dijital öğrenme platformları ve sanal gerçeklik teknolojileri, öğrencilere daha interaktif ve etkili bir eğitim imkanı sunuyor.\n\nBununla birlikte, teknolojinin etik ve sosyal sorumlulukları da göz ardı edilmemelidir. Veri güvenliği, yapay zeka etiği ve dijital uçurum gibi konular, teknolojinin sorumluluk bilinciyle ele alınması gereken önemli meselelerdir.\n\nTeknoloji, insanlığın sınırlarını ve hayal gücünü zorlayarak geleceğe yönelik sonsuz keşiflerin kapılarını açıyor. İnsanların teknolojiyi bilgelikle yönetmesi ve sosyal sorumluluk bilinciyle hareket etmesi, daha adil, güvenli ve sürdürülebilir bir dünya inşa etme yolunda önemli bir adımdır. Teknoloji, insan yaratıcılığının ilerlemeye dönüştüğü büyülü bir güçtür ve geleceğimizi şekillendirmede önemli bir role sahiptir.', 'Teknoloji, insan yaratıcılığının sınırlarını zorlayan ve sonsuz keşiflerin kapılarını açan bir güçtür. ', 'bilimselmerak.jpeg', 2, '2023-07-28 22:40:00', 'ardayilmaz', 40),
(75, 'Teknoloji: İnsanlığın Geleceğine Yön Veren Sonsuz İmkânlar Dünyası', 'Teknoloji, insanlığın tarihindeki en büyük devrimlerden biridir ve hızla gelişmeye devam ediyor. İnsan merakı ve yaratıcılığı sayesinde ortaya çıkan teknoloji, hayatımızı kökten değiştiriyor ve geleceğe yönelik sonsuz imkânlar sunuyor.\r\n\r\nDijital devrimle birlikte internetin yaygınlaşması ve bilgisayarların gücünün artması, dünyayı birbirine bağlayarak bilgiye anında erişim sağlıyor. Akıllı telefonlar ve akıllı cihazlarla hayatımızı daha verimli ve bağlantılı hale getiriyoruz. Yapay zeka, otomasyon ve nesnelerin interneti gibi teknolojiler, hayatımızın her alanında etkili bir şekilde kullanılıyor.\r\n\r\nTeknoloji, tıp alanında da devrim yaratıyor. Genetik araştırmalar, hastalıkların nedenlerini anlamamızı ve kişisel tıp uygulamalarını geliştirmemizi sağlıyor. Robotik cerrahi, ileri görüntüleme sistemleri ve yapay organlar, sağlık hizmetlerini daha kesin ve etkili hale getiriyor.\r\n\r\nEnerji ve çevre alanında da teknoloji büyük bir rol oynuyor. Temiz enerji kaynakları, enerji verimliliği ve çevresel koruma yöntemleri, iklim değişikliğiyle mücadelede önemli bir etki sağlıyor. Sürdürülebilirlik ve çevre dostu teknolojiler, doğal kaynakları koruyarak gelecek nesillere daha yaşanabilir bir dünya bırakma hedefini destekliyor.\r\n\r\nEğitimde teknoloji, öğrencilere daha etkili ve kişiselleştirilmiş bir eğitim imkânı sunuyor. Uzaktan eğitim, dijital öğrenme platformları ve sanal gerçeklik teknolojileri, öğrencilerin öğrenme deneyimini daha etkileşimli ve ilgi çekici hale getiriyor.\r\n\r\nAncak teknolojinin hızlı ilerleyişiyle birlikte, etik ve güvenlik konularına da özen göstermek gerekiyor. Veri gizliliği, yapay zeka etiği, siber güvenlik gibi konular, teknoloji kullanımının sorumlu bir şekilde yönetilmesini zorunlu kılıyor.\r\n\r\nTeknoloji, insanlığın geleceğine yön veren sonsuz imkânlar dünyasıdır. Doğru kullanıldığında insan yaşamını kolaylaştırır, bilgiye erişimi hızlandırır ve hayat kalitesini artırır. Teknoloji, insana ve çevreye duyarlı bir şekilde yönetildiğinde, insanlığın refahını ve ilerlemesini destekleyen güçlü bir araçtır.', 'Teknoloji, insanlığın tarihindeki en büyük devrimlerden biridir ve hızla gelişmeye devam ediyor.', 'pexels-christina-morillo-1181317.jpg', 2, '2023-08-12 20:30:00', 'melekaydin', 81),
(76, 'Büyülü Sanat Dünyası', 'Sanat, insanlığın duygularını, düşüncelerini ve hayal gücünü ifade etmek için kullandığı yaratıcı bir etkinliktir. Sanat, resim, heykel, müzik, edebiyat, dans, tiyatro ve daha pek çok disiplini içerir. İnsanlar sanat aracılığıyla iç dünyalarını dışa vurur, toplumsal mesajlar iletmeye çalışır ve dünyayı daha derin bir şekilde anlamaya çalışırlar.\r\n\r\nSanatın temel işlevlerinden biri estetik deneyim sunmaktır. Sanat yapıtları güzellik, uyum ve estetik değerler taşır, izleyicileri veya dinleyicileri etkileyerek duygusal ve zihinsel bir deneyim yaşatır. Sanatın güzellik arayışı, insanın yaşamındaki monotonluğu kırar ve ona yeni bir perspektif sunar.\r\n\r\nSanat, kültürel ifade biçimidir. Her toplumun sanatı kendi kültürel değerlerini, inançlarını ve tarihini yansıtır. Sanat, insanların kimliklerini, köklerini ve ortak değerlerini koruma ve aktarma işlevini üstlenir.\r\n\r\nSanat, toplumsal mesajların iletilmesinde önemli bir araçtır. Sanatçılar, çevresel, politik, sosyal veya duygusal konularda insanlara seslenir ve toplumsal değişimlere katkı sağlar. Sanat eserleri, insanların dünyayı anlamalarına, sorgulamalarına ve farkındalık kazanmalarına yardımcı olur.\r\n\r\nSanat, insanların duygusal ifadesini sağlar. Sanatçılar, iç dünyalarındaki duyguları sanat eserlerine yansıtarak kendi terapötik süreçlerini yaşarlar. Aynı zamanda izleyiciler veya dinleyiciler de sanat eserleri vasıtasıyla duygusal bir bağ kurar ve kendi duygusal deneyimlerini ifade ederler.\r\n\r\nSanat, yaratıcılığı destekleyen ve teşvik eden bir süreçtir. Sanatçılar, hayal güçlerini kullanarak yeni düşünceler, fikirler ve perspektifler oluştururlar. Bu yaratıcı süreç, bilim, teknoloji ve diğer alanlarda da inovasyonu teşvik eder.\r\n\r\nSanat, toplumun ve tarihin bir aynasıdır. Sanat eserleri, dönemlerin ve toplumların değerleri, zevkleri ve düşüncelerini yansıtır. Geçmişten günümüze, sanat eserleri geleceğe bir miras olarak kalır ve insanlığın kültürel hafızasını oluşturur.\r\n\r\nSonuç olarak, sanat insanlığın en değerli ifade biçimlerinden biridir. Duyguları ifade etmek, düşünceleri aktarmak, kültürel mirası korumak ve toplumsal değişime katkı sağlamak gibi önemli işlevleri vardır. Sanat, insanın iç dünyasını zenginleştiren, topluma katkı sağlayan ve yaşamı daha anlamlı kılan büyülü bir etkinliktir.', 'Sanat, insanlığın duygularını, düşüncelerini ve hayal gücünü ifade etmek için kullandığı yaratıcı bir etkinliktir. Sanat, resim, heykel, müzik, edebiyat, dans, tiyatro ve daha pek çok disiplini içerir.', 'pexels-jadson-thomas-542556.jpg', 3, '2023-08-22 00:45:27', 'melekaydin', 81),
(77, 'Moda: Kişisel Tarzın ve Yaratıcılığın Büyülü Dünyas', 'Moda, giyim, aksesuarlar, ayakkabılar ve diğer kişisel tarz unsurlarını içeren giyim ve tarzın değişken ve trende bağlı olarak şekillendiği bir kavramdır. Moda, insanların kişisel ifadesini yansıtma, toplumsal kimliğini gösterme ve kendini ifade etme şeklidir.\r\n\r\nModa, yüzyıllardır insanların yaşamında önemli bir rol oynamıştır. Giyim ve süs eşyaları, sadece fiziksel ihtiyaçları karşılamakla kalmaz, aynı zamanda sosyal ve kültürel bağlamda da önemli bir rol oynar. Moda, kişisel kimliği ve zevki yansıtmak için bir araç olarak kullanılır.\r\n\r\nModa dünyasında, sürekli değişen trendler ve stiller vardır. Moda, mevsimsel olarak değişen koleksiyonlar, defileler ve tasarım evleriyle sürekli olarak yenilenir. Moda endüstrisi, tasarımcılar, stilistler, mankenler ve diğer moda uzmanları aracılığıyla yaratıcılığın ve estetiğin birleştiği bir alanı temsil eder.\r\n\r\nModa, kültürlerarası bir dil olarak da kullanılır. Farklı coğrafyalardan ve kültürlerden gelen tasarımlar ve stiller, kültürel çeşitliliği kutlar ve farklı moda ifadeleri aracılığıyla insanları bir araya getirir.\r\n\r\nAncak moda dünyasında, sürdürülebilirlik ve etik konuları da önemlidir. Hızlı tüketim alışkanlıkları ve tekstil endüstrisinin çevresel etkileri, moda endüstrisinin sorumluluk duygusu ve çevre dostu yaklaşımlar gerektiren konular arasında yer alır.\r\n\r\nSonuç olarak, moda, giyim ve stilin değişken ve yaratıcı bir dünyasıdır. İnsanların kişisel ifadelerini ve tarzlarını yansıtmak için kullandığı bir araçtır. Moda, güzellik, estetik ve yaratıcılığın birleştiği büyülü bir alan olarak insan hayatının bir parçasıdır.', 'Moda, giyim, aksesuarlar, ayakkabılar ve diğer kişisel tarz unsurlarını içeren giyim ve tarzın değişken ve trende bağlı olarak şekillendiği bir kavramdır. ', 'pexels-evg-kowalievska-1381556.jpg', 5, '2023-08-02 00:00:00', 'melekaydin', 81),
(78, '\"Sanat: İnsanın Ruhunu ve Hayal Gücünü Yansıtan Büyülü Evren', '\r\nBaşlık: \"Sanat: İnsanın Ruhunu ve Hayal Gücünü Yansıtan Büyülü Evren\"\r\n\r\nSanat, insanlığın en güçlü ve büyülü ifade biçimlerinden biridir. Yüzyıllardır, insanlar duygularını, düşüncelerini ve hayal gücünü sanat aracılığıyla ifade etmiştir. Resim, heykel, müzik, edebiyat, dans, tiyatro ve daha pek çok disiplin, insanın iç dünyasını zenginleştirirken, toplumun tarihini ve kültürel mirasını koruyan bir aynadır.\r\n\r\nSanatın temel işlevlerinden biri, estetik deneyim sunmaktır. Sanat eserleri, güzellik, uyum ve estetik değerler taşır, izleyici veya dinleyicileri etkileyerek onlara duygusal ve zihinsel bir deneyim yaşatır. Sanatın estetik arayışı, insanın yaşamındaki monotonluğu kırar ve ona yeni bir perspektif sunar.\r\n\r\nSanat, kültürel ifade biçimidir. Her toplumun sanatı, kendi değerlerini, inançlarını ve tarihini yansıtır. Sanat, insanların kimliklerini, köklerini ve ortak değerlerini koruma ve aktarma işlevini üstlenir. Sanatçılar, kendi kültürlerinin ve coğrafyalarının zenginliklerini eserlerinde yansıtarak gelecek nesillere bir miras bırakır.\r\n\r\nSanat, toplumsal mesajların iletilmesinde önemli bir araçtır. Sanatçılar, çevresel, politik, sosyal veya duygusal konularda insanlara seslenir ve toplumsal değişimlere katkı sağlar. Sanat eserleri, insanların dünyayı anlamalarına, sorgulamalarına ve farkındalık kazanmalarına yardımcı olur.\r\n\r\nSanat, insanların duygusal ifadesini sağlar. Sanatçılar, iç dünyalarındaki duyguları sanat eserlerine yansıtarak kendi terapötik süreçlerini yaşarlar. Aynı zamanda izleyiciler veya dinleyiciler de sanat eserleri vasıtasıyla duygusal bir bağ kurar ve kendi duygusal deneyimlerini ifade ederler.\r\n\r\nSanat, yaratıcılığı destekleyen ve teşvik eden bir süreçtir. Sanatçılar, hayal güçlerini kullanarak yeni düşünceler, fikirler ve perspektifler oluştururlar. Bu yaratıcı süreç, bilim, teknoloji ve diğer alanlarda da inovasyonu teşvik eder.\r\n\r\nSanat, toplumun ve tarihin bir aynasıdır. Sanat eserleri, dönemlerin ve toplumların değerleri, zevkleri ve düşüncelerini yansıtır. Geçmişten günümüze, sanat eserleri geleceğe bir miras olarak kalır ve insanlığın kültürel hafızasını oluşturur.\r\n\r\nSonuç olarak, sanat insanlığın en değerli ifade biçimlerinden biridir. Duyguları ifade etmek, düşünceleri aktarmak, kültürel mirası korumak ve toplumsal değişime katkı sağlamak gibi önemli işlevleri vardır. Sanat, güzellik, estetik ve yaratıcılığın birleştiği büyülü bir alan olarak insan hayatının bir parçasıdır. Sanat, içimizdeki güzellikleri keşfetmek, düşüncelerimizi ifade etmek ve hayal gücümüzü özgürce yaşamak için bize sonsuz bir evren sunar.', 'Sanat, insanlığın en güçlü ve büyülü ifade biçimlerinden biridir. Yüzyıllardır, insanlar duygularını, düşüncelerini ve hayal gücünü sanat aracılığıyla ifade etmiştir.', 'pexels-olga-lioncat-7245308.jpg', 3, '2023-05-02 15:15:37', 'sedatekin', 79),
(79, 'Müzik: Duygulara Hitap Eden Büyülü Sesiyle Kalplerde Yankılanan Sanat', 'Müzik, insanlığın en evrensel ve büyülü sanat formlarından biridir. Ritm, melodi ve sözlerin harmonisiyle şekillenen müzik, insanların ruhuna ve duygularına dokunurken, dil, kültür ve coğrafya ayrımı gözetmeksizin tüm insanları bir araya getiren bir güce sahiptir.\r\n\r\nMüziğin temel amacı duygulara hitap etmektir. Sevinç, hüzün, aşk, keder gibi duygular, müzikle ifade bulur ve insanları derinden etkiler. Müziğin gücü, yaşanan duyguları paylaşma, teselli etme ve bir arada duygu yoğunluğu yaşama fırsatı sunar.\r\n\r\nMüzik, insanlar arasında bir bağ kurar. Ritimlerin ve melodilerin gücü, dans eden ayakları, ortak bir şarkı söyleyen kalabalığı ve aynı anda coşku dolu kalpleri bir araya getirir. Konserler ve festivaller, insanların ortak bir tutkuda birleşmesini ve müziğin büyüsünü birlikte yaşamasını sağlar.\r\n\r\nMüzik, tarihin bir yansımasıdır. Farklı dönemlerde ve kültürlerde üretilen müzikler, o dönemin ruhunu ve toplumun değerlerini yansıtır. Müzik eserleri, geçmişe bir bakış açısı sunar ve insanlığın kültürel mirasını korur.\r\n\r\nMüzik, yaratıcılığın ve kendini ifade etmenin bir aracıdır. Müzisyenler, kendi iç dünyalarını ve düşüncelerini eserlerine yansıtarak duygusal bir bağ kurarlar. Aynı şekilde, dinleyiciler de müziği kendilerine özgü bir şekilde yorumlar ve duygularını ifade ederler.\r\n\r\nMüzik, sağlık ve iyi oluş için de olumlu etkiler sunar. Duygusal terapi olarak kullanılan müzik, stresi azaltmaya, rahatlama sağlamaya ve ruh halini iyileştirmeye yardımcı olur. Müzik, zihni ve bedeni olumlu etkileyen bir iyilik kaynağıdır.\r\n\r\nAncak müzik dünyasında, ticari baskılar ve tüketim odaklı yaklaşımlar da yer alır. Müzisyenler ve sanatçılar, özgünlüğü koruma ve kaliteyi ön planda tutma sorumluluğu taşırlar. Gerçek sanatın ve ifade özgürlüğünün ticari kaygılarla baskı altında kalmasını önlemek önemlidir.\r\n\r\nSonuç olarak, müzik insanlığın en büyülü ve duygusal sanatlarından biridir. Duyguları ifade etme, insanları bir araya getirme ve kültürel mirası koruma gücüne sahiptir. Müzik, insanların iç dünyasını zenginleştirirken, kalplerde yankılanan büyülü sesiyle yaşamımıza anlam ve coşku katar. Müziğin gücü, insanlığın kalbinde sonsuz bir sevgi ve bağlılıkla yankılanır.', 'Müzik, insanlığın en evrensel ve büyülü sanat formlarından biridir. Ritm, melodi ve sözlerin harmonisiyle şekillenen müzik, insanların ruhuna ve duygularına dokunurken...', 'pexels-chris-alo-17371478.jpg', 4, '2023-08-22 20:00:00', 'sedatekin', 79),
(80, 'Moda Trendleri: Yaratıcılığın ve Değişimin Büyülü Yansımaları', 'Moda trendleri, giyim ve tarz alanında sürekli değişen yaratıcı ifadelerdir. Moda sezonları, tasarımcılar ve influencer\'lar tarafından belirlenen akımlar, tarzları güncellemeyi sağlar.', 'Moda trendleri, giyim ve tarz alanında sürekli değişen yaratıcı ifadelerdir. Moda sezonları, tasarımcılar ve influencer\'lar tarafından belirlenen akımlar, tarzları güncellemeyi sağlar.', 'pexels-skylar-kang-6045028.jpg', 5, '2023-08-02 23:40:00', 'sedatekin', 79),
(81, 'Dans Sanatı: Bedenin Ritmiyle Büyülü Estetik ve Duygusal İfadenin Dansı', 'Dans, bedensel hareketleri ritim, müzik ve duyguyla birleştirerek estetik bir ifade sunan ve insanların duygusal, fiziksel ve zihinsel deneyimlerini yansıtan bir sanat dalıdır. Dans, tarih boyunca farklı kültürlerde, toplumlarda ve dönemlerde çeşitli amaçlarla kullanılmıştır. Hem bireysel hem de grup olarak icra edilen danslar, enerjiyi ifade etme, hikayeler anlatma, toplumsal bağları güçlendirme ve estetik bir deneyim yaşama amacı güder.\n\nDansın Çeşitleri:\n\nKlasik Bale: Düzenli ve özgün hareketlerle karakterleri ve hikayeleri ifade eden dans türüdür. Özel bale ayakkabıları ve teknikleriyle bilinir.\n\nModern Dans: Duygusal ifadenin ve özgürlüğün ön planda olduğu dans türüdür. Yerçekimini meydan okuyan hareketler ve deneysel yaklaşımlar içerir.\n\nHalk Dansları: Farklı kültürlerin geleneksel danslarını içeren kategoridir. Toplumun tarihini, değerlerini ve yaşam tarzını yansıtır.\n\nCaz Dansı: Canlı müziğe dayalı, enerjik ve ritmik bir dans türüdür. İmprovizasyon ve serbest hareketler içerir.\n\nHip-Hop ve Sokak Dansları: Gençlik kültürünün bir parçası olarak ortaya çıkan, enerjik ve ritmik dans hareketlerini içeren türdür.\n\nLatin Dansları: Salsa, tango, rumba gibi hareketli ve duygusal danslar Latin kökenlidir. Partner dansları olarak bilinirler.\n\nDansın Önemi ve Etkileri:\n\nDuygusal İfade: Dans, duyguları ve içsel dünyayı ifade etmenin güçlü bir yoludur. İnsanlar içlerinde hissettiklerini bedenleriyle ifade ederek rahatlayabilirler.\n\nFiziksel Sağlık: Dans, fiziksel aktivitenin bir yolu olarak vücudu güçlendirir, esnekliği artırır ve kardiyovasküler sağlığı destekler.\n\nSosyal Bağlar: Topluluk içinde dans etmek, insanlar arasında birlik ve dayanışmayı artırabilir. Grup dansları, toplulukların bir arada eğlenmesini sağlar.\n\nKültürel Miras: Halk dansları ve geleneksel danslar, kültürel kimliği ve tarihi yansıtarak gelecek nesillere aktarır.\n\nStres Azaltma: Dans etmek, stresi azaltabilir, zihinsel rahatlamayı destekleyebilir ve zihni boşaltmaya yardımcı olabilir.\n\nDans, bedenin ritmi ve müziğiyle etkileyici bir görsel deneyim sunar. İnsanların iç dünyalarını ifade etmelerine, enerjilerini boşaltmalarına ve başkalarıyla iletişim kurmalarına olanak tanır. Dans, duygusal ifadenin, fiziksel sağlığın ve kültürel mirasın büyülü bir aracıdır.', 'Dans, bedensel hareketleri ritim, müzik ve duyguyla birleştirerek estetik bir ifade sunan ve insanların duygusal, fiziksel ve zihinsel deneyimlerini yansıtan bir sanat dalıdır. ', 'pexels-wellington-cunha-1918445.jpg', 3, '2023-09-02 01:00:00', 'zeynepaslan22', 73),
(82, 'Müzik Aletleri: Sesin Büyülü Yolculuğunda Estetik ve Duygusal Serüven', 'Müzik aletleri, insanların duygusal ifade ve estetik deneyim yaşadığı önemli araçlardır. Farklı türlerde ve formlarda müzik aletleri bulunur. Her bir alet, özgün sesleri ve karakteristik özellikleriyle dikkat çeker. Bu aletler, ritim, melodi ve harmoni oluşturarak müziğin temel taşlarından birini oluşturur.\r\n\r\nYaylı çalgılar, telleri yaylarla çekerek çalınır ve orkestraların temel üyeleridir. Kemanın zarif tınıları, viyola ve çellonun derin sesleriyle birleşir. Nefesli çalgılar, üflenerek çalınır ve melodilere karakteristik tonlar katar. Flütün hafif sesi, klarnetin sıcak tonu ve trompetin parlak tınıları dinleyiciye farklı duygusal deneyimler yaşatır.\r\n\r\nTuşlu çalgılar, tuşları çalarak ses elde eder. Piyano, geniş tını yelpazesiyle hem solo performanslarda hem de orkestraların merkezinde yer alır. Vurmalı çalgılar ise ritm ve vuruşları oluşturur. Davulun güçlü ritmi ve xylophone\'un kristal gibi tınıları, müziğe enerji ve renk katar.\r\n\r\nTelliler, telleri parmaklar veya penalarla çalınarak çeşitli sesler üretir. Gitarın zarif akorları, bağlamanın halk müziğine özgü tınıları ve ukulele\'nin neşeli notası, farklı müzik türlerinin anahtarıdır. Elektronik müzik aletleri ise modern teknolojinin eseri olarak elektronik devrelerle ses üretir. Synthesizer\'ın dijital tınıları ve elektrikli gitarın çarpıcı akorları, çağdaş müziğin bir parçasını oluşturur.\r\n\r\nMüzik aletleri, insanların duygusal ifadelerini ve yaratıcılıklarını dışa vurmalarını sağlar. Farklı tınılar, melodiler ve ritimler aracılığıyla müziğin büyülü dünyasını oluştururlar. Her bir alet, müziğin dokusuna benzersiz bir renk ve derinlik katarak, dinleyicilere unutulmaz deneyimler sunar.', 'Müzik aletleri, insanların duygusal ifade ve estetik deneyim yaşadığı önemli araçlardır. Farklı türlerde ve formlarda müzik aletleri bulunur. Her bir alet, özgün sesleri ve karakteristik özellikleriyle dikkat çeker. ', 'pexels-cristian-benavides-2049414.jpg', 4, '2023-08-02 14:00:00', 'zeynepaslan22', 73),
(83, 'Moda: Estetik ve Kişisel İfadenin Büyülü Dünyası', 'Moda, giyim, aksesuarlar ve tarzın sürekli değişen ve dönüşen dünyasını ifade eder. Tarih boyunca insanlar, giyim ve süs eşyaları aracılığıyla kendilerini ifade etmiş ve toplum içinde farklılıklarını vurgulamışlardır. Moda, sadece günlük giyim değil, aynı zamanda sanatsal ve estetik bir ifade biçimidir.\r\n\r\nModa, her mevsim ve yıl farklı trendlerle gelişir. Moda endüstrisi, tasarımcıların, stilistlerin ve sanatçıların yaratıcılığını yansıtarak güncel koleksiyonlar ve stiller sunar. Moda haftaları ve defileler, yeni trendlerin belirlendiği ve moda dünyasının nabzının tutulduğu önemli etkinliklerdir.\r\n\r\nModa, kültürel çeşitlilik ve kimlik ifadesiyle derin bir bağ içerir. Farklı toplumlar ve coğrafyalar, kendi giyim tarzlarını ve süs eşyalarını yaratmış ve miras olarak gelecek nesillere aktarmışlardır. Bu sayede moda, kültürel çeşitliliği ve tarihi yansıtan önemli bir sanat ve ifade aracı olmuştur.\r\n\r\nSürdürülebilirlik ve etik modanın önemi, günümüzde artan bir şekilde vurgulanmaktadır. Hızlı tüketim ve tekstil atıkları, çevresel ve sosyal sorunlara yol açarken, sürdürülebilir moda ve geri dönüşümlü malzemelerle ilgilenen tasarımcılar, modanın geleceğini daha bilinçli ve çevre dostu bir şekilde yönlendirmeyi amaçlamaktadır.\r\n\r\nModa, bireylerin kişisel tarzlarını ifade etme ve kendilerini rahat hissetme yolu olmanın yanı sıra, toplumsal etkileri de vardır. Moda, toplumsal cinsiyet rolleri, sınıf farklılıkları ve kişisel kimlik üzerinde etkili olabilir.\r\n\r\nSonuç olarak, moda, giyim ve tarzın sanatsal ve estetik bir ifade biçimidir. Her dönemde değişen ve gelişen moda trendleri, yaratıcılığın ve estetiğin yansımalarıdır. Moda, kültürel mirasın ve bireysel kimliklerin bir araya geldiği büyülü bir dünyadır. Bu alanda, sürdürülebilirlik ve etik kaygıların önemi giderek artmaktadır ve modanın geleceği üzerinde olumlu bir etkiye sahip olacaktır. Moda, insanların iç dünyalarını ve tarzlarını ifade etme özgürlüğünü sunarken, toplum içinde etkileyici bir bağ oluşturan önemli bir sanattır.', 'Moda, giyim, aksesuarlar ve tarzın sürekli değişen ve dönüşen dünyasını ifade eder. Tarih boyunca insanlar, giyim ve süs eşyaları aracılığıyla kendilerini ifade etmiş ve toplum içinde farklılıklarını vurgulamışlardır. ', 'eAcD3xCM00fWpL2txre4zA_b.jpg', 5, '2023-08-02 00:00:00', 'selinkaraca', 71),
(84, 'Kişisel Gelişim: Potansiyelin Keşfi ve İçsel Dönüşümün Büyülü Yolculuğu', 'Kişisel gelişim, bireylerin potansiyellerini keşfetmeye ve kendilerini geliştirmeye yönelik sürekli bir çaba ve öğrenme sürecidir. Kişisel gelişim, fiziksel, zihinsel, duygusal ve ruhsal alanlarda bireylerin yeteneklerini artırmayı ve kendilerini daha iyi bir hale getirmeyi hedefler. Bu süreç, yaşam boyu devam eder ve herkes için farklılık gösterebilir.\r\n\r\nKişisel gelişimin önemli unsurlarından biri, kendini tanıma ve farkındalık geliştirme sürecidir. Kendini anlamak, güçlü ve zayıf yönleri tanımlamak, tutkularını ve hedeflerini belirlemek, kişinin kendi hayatını yönlendirebilmesi ve daha mutlu bir yaşam sürmesi için temel adımlardır.\r\n\r\nBu süreçte, kendine güven, olumlu düşünce, motivasyon ve hedef belirleme gibi beceriler geliştirilir. Kişisel gelişim, olumlu bir yaşam tarzı benimsemek, stresle başa çıkma ve ilişkilerde sağlıklı iletişim gibi konularda bireyleri güçlendirebilir.\r\n\r\nKişisel gelişimin yöntemleri arasında, kitaplar ve makaleler okumak, seminer ve eğitimlere katılmak, koçluk hizmetlerinden yararlanmak ve kişisel çalışmalar yapmak gibi çeşitli araçlar bulunur. İnsanlar, bu araçları kullanarak içsel potansiyellerini keşfedebilir, yeteneklerini geliştirebilir ve daha iyi bir yaşam kalitesine sahip olabilir.\r\n\r\nKişisel gelişimin faydaları sadece bireylerle sınırlı kalmaz, aynı zamanda topluma da olumlu etkileri vardır. Bireyler, kendilerini daha iyi hissettiklerinde, daha mutlu ve başarılı olurlar. Bu da toplumun genel refahını artırır ve daha pozitif bir etki yaratır.\r\n\r\nSonuç olarak, kişisel gelişim, bireylerin potansiyellerini keşfetmeye ve kendilerini geliştirmeye yönelik önemli bir süreçtir. Kendini tanıma, farkındalık geliştirme, olumlu düşünce ve hedef belirleme gibi adımlarla kişiler, içsel güçlerini ve yeteneklerini ortaya çıkararak daha tatmin edici ve mutlu bir yaşam sürebilirler.', '\nKişisel gelişim, bireylerin potansiyellerini keşfetmeye ve kendilerini geliştirmeye yönelik sürekli bir çaba ve öğrenme sürecidir. ', 'pexels-maik-kleinert-3576284.jpg', 6, '2023-08-02 00:00:00', 'ayseyilmaz', 66),
(85, 'Kişisel Gelişim: Kendini Tanı, Potansiyelini Keşfet ve Daha İyi Bir Sen Ol', 'Kişisel gelişim, hayatımızın her aşamasında süren bir yolculuktur. Bu yolculukta, içsel dönüşüm ve büyüme için çeşitli araçlar kullanırız. Her bireyin kendine özgü yetenekleri ve potansiyelleri vardır ve kişisel gelişim, bu potansiyelleri keşfetmek ve en iyi versiyonumuzu ortaya çıkarmak için tasarlanmıştır.\r\n\r\nİlk adım, kendini tanımaktır. Kendimizi tanıyarak güçlü ve zayıf yönlerimizi belirleyebiliriz. Bu farkındalık, kendi davranışlarımızı anlamamıza ve olumlu değişiklikler yapmamıza yardımcı olur. Kendini tanımak, içsel yolculuğumuzun temel taşıdır.\r\n\r\nBir sonraki adım, hedef belirlemektir. Hayattan ne istediğimizi ve nasıl bir yaşam sürmek istediğimizi belirlemek önemlidir. Hedefler, bize motivasyon ve odaklanma sağlar. Belirlediğimiz hedeflere doğru ilerlemek, kişisel gelişim yolculuğumuzda bizi ileriye taşır.\r\n\r\nOlumlu düşünce ve inançlar, kişisel gelişimin temel taşlarındandır. Negatif düşünceler ve inançlar bizi kısıtlayabilir ve ilerlememize engel olabilir. Bu nedenle, pozitif bir zihin yapısı geliştirmek ve olumlu düşünmek, içsel gücümüzü ortaya çıkarmada önemlidir.\r\n\r\nKişisel gelişim süreci, sürekli öğrenme ve gelişme üzerine kuruludur. Yeni beceriler öğrenmek, farklı deneyimler yaşamak ve kendimizi geliştirmek için çaba göstermek, hayatımızı daha zengin ve anlamlı kılar.\r\n\r\nAynı zamanda, kendi kendimize acımasız olmaktan kaçınmalıyız. İlerlemenin bir süreç olduğunu ve zaman zaman hatalar yapabileceğimizi kabul etmeliyiz. Başarısızlıkların bizi durdurmaması ve tekrar denemeye cesaret etmemiz, kişisel gelişim yolculuğumuzda önemlidir.\r\n\r\nKişisel gelişim, hayatımızın her alanına dokunan bir süreçtir. Sağlıklı ilişkiler kurmak, kariyer hedeflerimize ulaşmak, duygusal zekamızı geliştirmek, fiziksel sağlığımıza dikkat etmek gibi pek çok farklı boyutu içerir. Kendimizi keşfetmek ve geliştirmek, bize daha dengeli ve tatmin edici bir hayat sunar.\r\n\r\nSonuç olarak, kişisel gelişim, içsel dönüşüm ve büyüme için önemli bir yolculuktur. Kendini tanımak, hedef belirlemek, olumlu düşünmek, sürekli öğrenmek ve kendimize karşı şefkatli olmak, kişisel gelişim yolculuğumuzda bizi destekleyen anahtar unsurlardır. Bu süreçte, içsel gücümüzü keşfeder ve potansiyelimizi gerçekleştiririz. Hayatımızı daha tatmin edici ve anlamlı kılan bu yolculuk, bizi daha iyi bir sen olmaya götürür.', 'Kişisel gelişim, hayatımızın her aşamasında süren bir yolculuktur. Bu yolculukta, içsel dönüşüm ve büyüme için çeşitli araçlar kullanırız.', 'istockphoto-1143043276-612x612.jpg', 6, '2023-08-02 00:00:00', 'ahmetyildirim', 80),
(86, 'Keşiflerle Dolu Macera: Seyahat Etmek ve Dünyayı Kucaklamak', 'Seyahat, insanların farklı yerleri keşfetmek, yeni kültürleri deneyimlemek ve unutulmaz anılar biriktirmek için yaptığı büyülü bir yolculuktur. Tarih boyunca insanlar, keşifler yapmak, ticaret yapmak, kültürel etkileşimlerde bulunmak ve macera arayışıyla seyahat etmişlerdir. Günümüzde ise seyahat, insanların hayatlarını zenginleştiren ve perspektiflerini genişleten önemli bir aktivite olarak devam etmektedir.\r\n\r\nSeyahatin birçok faydası vardır. Öncelikle, farklı yerleri gezip görmek, yeni kültürleri ve gelenekleri tanımak, insanların hoşgörüsünü ve anlayışını artırır. Farklı coğrafyalarda insanlarla etkileşime geçmek, kültürel farklılıkları anlamak ve saygı duymak için önemli bir fırsattır.\r\n\r\nSeyahat etmek, öğrenme ve keşfetme arzusunu besler. Yeni yerlerde gezerken, tarihi ve doğal güzellikleri görmek, yerel lezzetleri tatmak ve yerel sanat ve el sanatlarını incelemek insanlara öğrenme zevkini sunar. Yeni deneyimler ve bilgilerle dolu seyahatler, kişisel gelişim ve olgunlaşmaya katkıda bulunur.\r\n\r\nSeyahat aynı zamanda stresi azaltma ve ruh halini yükseltme potansiyeline sahiptir. Yoğun iş temposu ve günlük rutinlerden uzaklaşıp, farklı bir ortamda dinlenmek ve eğlenmek, insanların zihinsel ve duygusal rahatlama sağlamasına yardımcı olur.\r\n\r\nSeyahat etmek, insanları doğal güzelliklerle ve çeşitli etkinliklerle buluşturur. Doğa yürüyüşleri, plaj keyfi, dağ tırmanışı gibi etkinlikler, doğayla iç içe olma fırsatı sunar ve bedensel sağlığı destekler.\r\n\r\nBununla birlikte, seyahat etmek çevresel ve sosyal sorumlulukları da içerir. Sürdürülebilir turizm ve çevre dostu uygulamalar, doğal ve kültürel mirasın korunması için önemlidir. Yerel topluluklara saygı göstermek ve kültürel duyarlılıkla davranmak, etik seyahat etmenin temelidir.\r\n\r\nSonuç olarak, seyahat, keşif, öğrenme ve unutulmaz deneyimlerle dolu büyülü bir yolculuktur. Farklı yerleri gezip görmek, yeni kültürleri tanımak ve insanlarla etkileşime geçmek, hayatımızı zenginleştirir ve hoşgörümüzü artırır. Aynı zamanda, doğanın ve çevrenin tadını çıkarmak, stresi azaltmak ve ruh halini yükseltmek için önemli bir fırsattır. Ancak seyahat ederken çevresel ve sosyal sorumlulukları göz ardı etmemek, etik ve sürdürülebilir bir şekilde seyahat etmek de büyük önem taşır.', 'Seyahat, insanların farklı yerleri keşfetmek, yeni kültürleri deneyimlemek ve unutulmaz anılar biriktirmek için yaptığı büyülü bir yolculuktur.', 'pexels-nappy-1058959.jpg', 7, '2023-08-02 00:00:00', ' canozturk', 65),
(87, 'Teknoloji: İnsanlığın Dijital Dönüşümünde Büyülü Güç', 'Teknoloji, insan yaşamını köklü bir şekilde değiştiren ve geliştiren bilgi ve becerilerin uygulanmasıdır. İnsanlar, ihtiyaçlarını karşılamak, günlük yaşamlarını kolaylaştırmak, iletişim kurmak, bilgiye erişmek, yeni keşifler yapmak ve üretkenliklerini artırmak için teknolojiden yararlanırlar. Tarih boyunca teknolojik ilerlemeler, toplumların gelişimini ve evrimini şekillendirmiştir.\r\n\r\nTeknolojinin önemli bir parçası olan bilgisayarlar ve internet, günümüzdeki dijital çağın temelini oluşturur. İnternet, dünya genelindeki insanları birbirine bağlayarak iletişimi ve bilgi akışını hızlandırır. Bilgisayarlar, iş hayatından eğlenceye, araştırmadan sanat ve tasarıma kadar pek çok alanda kullanılır.\r\n\r\nMobil cihazlar, akıllı telefonlar ve tabletler, her yerde internete erişimi sağlayarak hayatımızı kolaylaştırır ve bilgiye anında ulaşım imkanı sunar. İletişimde büyük bir devrim yaratan bu cihazlar, aynı zamanda mobil uygulamalar sayesinde birçok işi hızlandırır ve verimliliği artırır.\r\n\r\nYapay zeka ve makine öğrenimi gibi teknolojiler, bilgisayar sistemlerini insan benzeri görevleri yerine getirebilecek hale getirir. Otomasyon ve robot teknolojileri, üretim süreçlerinde ve endüstriyel alanlarda verimliliği artırırken, sağlık sektöründe de önemli gelişmeler sağlar.\r\n\r\nEğitim alanında teknoloji, uzaktan eğitim ve çevrim içi kaynaklarla öğrenme fırsatlarını genişletir. Sanat ve tasarım alanında dijital medya ve grafik tasarım, yeni yaratıcı imkanlar sunar. Sağlık teknolojileri, tanı ve tedavi süreçlerini iyileştirerek yaşam kalitesini artırır.\r\n\r\nSürdürülebilirlik ve çevre konularında da teknoloji büyük bir rol oynar. Temiz enerji kaynakları, enerji verimliliği, geri dönüşüm teknolojileri, iklim değişikliğiyle mücadelede etkili çözümler sunar.\r\n\r\nAncak teknolojinin hızlı ilerlemesi, etik ve güvenlik konularını da gündeme getirir. Veri gizliliği, yapay zeka etiği, siber güvenlik ve teknolojinin insanlığın refahına olan etkileri gibi konular dikkate alınmalıdır.\r\n\r\nTeknoloji, bilim ve insanlığın işbirliğiyle ilerlerken, insanların refahını artırma ve toplumsal eşitlik için kullanılması büyük önem taşır. Teknoloji, insan hayatını ve toplumları dönüştürme potansiyeline sahip büyülü bir güçtür.', 'Teknoloji, insan yaşamını köklü bir şekilde değiştiren ve geliştiren bilgi ve becerilerin uygulanmasıdır. ', 'pexels-dzenina-lukac-930530.jpg', 2, '2023-08-02 00:00:00', 'mehmetakcay', 69);

-- --------------------------------------------------------

--
-- Table structure for table `kategori`
--

CREATE TABLE `kategori` (
  `kategori_id` int(11) NOT NULL,
  `kategori_ad` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

--
-- Dumping data for table `kategori`
--

INSERT INTO `kategori` (`kategori_id`, `kategori_ad`) VALUES
(1, 'Bilim'),
(2, 'Teknoloji'),
(3, 'Sanat'),
(4, 'Müzik'),
(5, 'Moda'),
(6, 'Kişisel Gelişim'),
(7, 'Seyahat');

-- --------------------------------------------------------

--
-- Table structure for table `kullanici`
--

CREATE TABLE `kullanici` (
  `kullanici_id` int(11) NOT NULL,
  `ad` varchar(15) NOT NULL,
  `soyad` varchar(15) NOT NULL,
  `eposta` varchar(50) NOT NULL,
  `sifre` longtext NOT NULL,
  `kullanici_adi` varchar(50) NOT NULL,
  `profil_foto` varchar(355) NOT NULL,
  `yetki` int(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

--
-- Dumping data for table `kullanici`
--

INSERT INTO `kullanici` (`kullanici_id`, `ad`, `soyad`, `eposta`, `sifre`, `kullanici_adi`, `profil_foto`, `yetki`) VALUES
(40, 'Arda', 'Yılmaz', 'ardayilmaz@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', 'ardayilmaz', '../profil_fotograflari/e2.jpg', 1),
(65, 'Can', 'Öztürk', 'canozturk@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', 'canozturk', '../profil_fotograflari/e3.jpg', 1),
(66, 'Ayşe', 'Yılmaz', 'ayseyilmaz@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', 'ayseyilmaz', '../profil_fotograflari/k10.jpg', 1),
(69, 'Mehmet', 'Akçay', 'mehmetakcay@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', 'mehmetakcay', '../profil_fotograflari/e4.jpg', 1),
(71, 'Selin', 'Karaca', 'selinkaraca@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', 'selinkaraca', '../profil_fotograflari/k4.jpg', 1),
(73, 'Zeynep', 'Aslan', 'zeynepaslan@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', 'zeynepaslan22', '../profil_fotograflari/k5.jpg', 1),
(78, 'Emre', 'Çelik', 'emrecelik@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', 'emrecelik32', '../profil_fotograflari/e5.jpg', 1),
(79, 'Seda', 'Tekin', 'sedatekin@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', 'sedatekin', '../profil_fotograflari/k7.jpg', 1),
(80, 'Ahmet', 'Yıldırım', 'ahmetyildirim@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', 'ahmetyildirim', '../profil_fotograflari/e6.jpg', 1),
(81, 'Melek', 'Aydın', 'melekaydin@gmail.com', '827ccb0eea8a706c4c34a16891f84e7b', 'melekaydin', '../profil_fotograflari/k8.jpg', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blog_yazi`
--
ALTER TABLE `blog_yazi`
  ADD PRIMARY KEY (`icerik_id`),
  ADD KEY `fk_blog_yazi_kullanici_id` (`yayinlayan_kullanici`);

--
-- Indexes for table `kategori`
--
ALTER TABLE `kategori`
  ADD PRIMARY KEY (`kategori_id`);

--
-- Indexes for table `kullanici`
--
ALTER TABLE `kullanici`
  ADD PRIMARY KEY (`kullanici_id`),
  ADD UNIQUE KEY `eposta` (`eposta`),
  ADD UNIQUE KEY `kullanici_adi` (`kullanici_adi`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blog_yazi`
--
ALTER TABLE `blog_yazi`
  MODIFY `icerik_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=122;

--
-- AUTO_INCREMENT for table `kategori`
--
ALTER TABLE `kategori`
  MODIFY `kategori_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=29;

--
-- AUTO_INCREMENT for table `kullanici`
--
ALTER TABLE `kullanici`
  MODIFY `kullanici_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=119;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `blog_yazi`
--
ALTER TABLE `blog_yazi`
  ADD CONSTRAINT `fk_blog_yazi_kullanici_id` FOREIGN KEY (`yayinlayan_kullanici`) REFERENCES `kullanici` (`kullanici_id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
